config/routes.rb
Rails.application.routes.draw do
  root "users#new"  
  get "users/" => "users#index"
  get "signup" => "users#new", as: :new_user
  post "users/" => "users#create"
  get "users/:id" => "users#show", as: :user

  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy"
  get "users/:id/questions" => "questions#index", as: :users_questions
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  get "questions/" => "questions#index"
  get "questions/new" => "questions#new", as: :new_question
  get "questions/:id/" => "questions#show", as: :question
  get "questions/:id/edit" => "questions#edit", as: :edit_question
  patch "questions/:id" => "questions#update"
  post "questions/:id/answers" => "answers#create", as: :question_answers
  delete "questions/:id" => "questions#destroy"
  post "questions/" => "questions#create"
  

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
    belongs_to :user
    belongs_to :question
    
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers


  # validates :username, presence: true
  # validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  # validates :password, presence: true, confirmation: true, length: { in: 6..20 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  attr_reader :password

  def password=(unencrypted_password)
    unless unencrypted_password.empty?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password) 
    end  
  end

  def authenticate(unencrypted_password)
    if BCrypt::Password.new(self.password_digest) == unencrypted_password
      return self
    else
      return false  
    end
  end

  # validations
  validates :username, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true, confirmation: true, length: { in: 6..20 }

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		@question = Question.find(params[:id])
		@answer = @question.answers.new(params.require(:answer).permit(:title, :body))
		@answer.save
		 redirect_to question_path(@question)
 	 end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  include SessionsHelper
 private
def current_user
 @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
    	    @questions = Question.all
    end

    def create
          # @user =  User.find(params[:id])
          @question = Question.new(params.require(:question).permit(:title, :body))
          if @question.save
          redirect_to questions_path(@question)
        end
    end

    def show
    	@question = Question.find(params[:id])
      @answer = Answer.new

    end

    def new
      @question = Question.new
    end

    def edit
        @question = Question.find(params[:id])
    end

    def update
      @question = Question.find(params[:id])
      if @question.update_attributes(params.require(:question).permit(:title, :body))
        redirect_to questions_path
      else
        render :edit
      end
    end

    def destroy
        @question = Question.find(params[:id])
        @question.destroy
        redirect_to questions_path
    end

    

   
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end

    def create
    	user = User.find_by(email: params[:login][:email])

      if user && user.authenticate(params[:login][:password])
         session[:user_id] = user.id.to_s
         redirect_to users_path
       else
          redirect_to login_path
       end 
      end
    

    def destroy
      session.delete(:user_id)
      redirect_to login_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    # @question = Question.find(params[:id])
  end

   def new
    @user = User.new
   end

   def create
  @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id.to_s
    flash[:welcome] = "Thanks for signing up, #{@user.username}!"
    redirect_to users_path
  else
    render :new
  end
end

   def edit
    @user = User.find(params[:id])
   end

   def update
      @user = User.find(params[:id])

      if @user.update_attributes(user_params)    
            redirect_to users_path
      else
        render :edit      
      end
   end

   def destroy
     @user = User.find(params[:id])
     @user.destroy
     redirect_to users_path
   end

   private
   def user_params
      params.require(:user).permit(:username, :email, :password)
   end

      private
            def require_login
               unless logged_in?
                flash[:error] = "You must be logged in to access that page."
                redirect_to login_path
            end
      end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def logged_in?
      session[:user_id] != nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HydeNseek</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <% if flash[:welcome] %>
    <h4 class="bg-success flash"><%= flash[:welcome] %></h4>
<% end %>

 <% if flash[:error] %>
    <h4 class="bg-danger flash"><%= flash[:error] %></h4>
<% end %>

<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<h1>Edit this Shnaz!</h1>


<%= form_for @question do | f | %>

    <div>
            <%= f.label :title %>
            <%= f.text_field :title %>
     </div>

     <div>
            <%= f.label :body%>
            <%= f.text_field :body %>
     </div>

 <%= f.submit "Submit these changes!", class: "btn btn-success" %>
<% end %>

<%= link_to "Back to the list!", question_path,class: "btn btn-primary"  %>

app/views/questions/index.html.erb
<div class="container-fluid">
  <div class="row">
  <div class="center">
  <h1>This is the Questions index</h1>
 <h1><%= current_user.username %></h1>
  <% if logged_in? %>
  Logged in as: <%= current_user.username %> <%= link_to 'Log Out', logout_path, method: :delete %>
<% else %>
  <%= link_to 'Log In', login_path %>
<% end %>

 
      <ul>
          <% @questions.each do | question | %>
              <li>
                   <strong><%= question.title %></strong>
                   <%= question.body %>
                   <%= link_to "Show Question", question_path(question)%>


                   
              </li>
          <% end %>
      </ul>
      <%= link_to "Add new question", new_question_path, class: "btn btn-info"%>
          
       </div>
      </div>

</div>

app/views/questions/new.html.erb
<div class="answer">

<section>
        <h2>Riddle me this!</h2>
        <%= form_for [@user, @question] do | f |%>

            <div>
              <%= f.label :title %>
              <%= f.text_field :title %>
            </div>

            <div>
              <%= f.label :body, "Question" %>
              <%= f.text_area :body %>
            </div>

            <%= f.submit "Answers To Follow",class: "btn btn-primary" %>

        <% end %>    
</section>

</div>

app/views/questions/show.html.erb
<div class="container-fluid"></div>

      <div class="jumbotron" >
           
          
        <section>
                <!-- <h2>This is  question  <%= @question.id %> </h2> -->
                <h2>  <%= @question.title %> </h2>
                <h4> <strong>Body: <%= @question.body %></strong> </h4>
        </section>

      </div>

      <div class="center">
        <section>
            <h1>Answers</h1>
            <%@question.answers.each do |answer|%>
                <div>
                      <h5><%= answer.body%></h5>
                </div>
            <% end %>  
        </section>
   <div class="row">

        

        <section class="col-lg-4">
               <h2 class="text-success">Answer that Ish!</h2>
               <%= form_for [@question, @answer] do |f|%>

                    <div>
                          <%= f.label :body%>
                          <%= f.text_area :body%>
                    </div>

                    <%= f.submit "Answer that Ish!" %>
              <% end %>

              <%= link_to "Edit question", edit_question_path(@question),class: "btn btn-primary" %>
              <%= link_to "Back to question!", questions_path,class: "btn btn-primary" %>
              <%= link_to "Delete this question!", question_path, method: :delete, data: {confirm: "Are you sure you want to delete this question?"}, class: "btn btn-warning"   %>
             
        </section>

        </div>
        
</div>

app/views/users/edit.html.erb
<h1>Edit this Shnaz!</h1>
    <% if @user.errors.any? %>
      <div>

        <h4 class="text-danger"><%= pluralize(@user.errors.count, "error") %> prevented you from signing up for an account:</h4>

        <ul class="list-group">
          <% @user.errors.full_messages.each do |msg| %>   
            <li class="list-group-item list-group-item-danger"><%= msg.downcase %></li>
          <% end %>
        </ul>            

  </div>
<% end %>

<%= form_for @user do | f | %>

<div>
        <%= f.label :username %>
        <%= f.text_field :username %>
 </div>

 <div>
        <%= f.label :email%>
        <%= f.text_field :email %>
    </div>

    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    
 <%= f.submit "Submit these changes!" %>


<% end %>

<%= link_to "Back to the list!", users_path %>

app/views/users/index.html.erb
<div class="center">

    <div class="container-fluid">
      <div class="row">
      <h1>This is the User index</h1>
     <h1><%= current_user.username %></h1>
      <% if logged_in? %>
      Logged in as: <%= current_user.username %> <%= link_to 'Log Out', logout_path, method: :delete %>
        <% else %>
      <%= link_to 'Log In', login_path %>
    <% end %>

      </div>

    <ul>
        <% @users.each do | user | %>
            <li>
                 <strong><%= user.username %></strong>
                 <%= user.email %>
                 

                 <%= link_to "View User", user_path(user) %>
            </li>
        <% end %>
    </ul>
    <%= link_to "Add new user", new_user_path, class: "btn btn-info"%>
    <%= link_to "Ask Q", new_question_path, class: "btn btn-info"%>
    </div>

</div>

app/views/users/new.html.erb
<div class="center">

<h1> Add a new User!</h1>
<%= form_for @user do |f| %>

<% if @user.errors.any? %>
  <div>

    <h4 class="text-danger"><%= pluralize(@user.errors.count, "error") %> prevented you from signing up for an account:</h4>

    <ul class="list-group">
      <%=@user.errors.full_messages.each do |msg| %>   
        <li class="list-group-item list-group-item-danger"><%= msg.downcase %></li>
      <% end %>
    </ul>            

  </div>
<% end %>


    <div>
        <%= f.label :username %>
        <%= f.text_field :username %>
    </div>

    <div>
        <%= f.label :email%>
        <%= f.text_field :email %>
    </div>

    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    

   
    <%= f.submit "Add new user!" %>

<% end %>

<%= link_to "Back to the list!", users_path %>




</div>

app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>

<section>
    <%= @user.email%>
</section>


<p> This user is <%= @user.username %> 
<%=@user.email %></p>
<%= link_to "Edit user", edit_user_path(@user)%>
<%= link_to "Back to user!", users_path%>
<%= link_to "Delete this User!", user_path, method: :delete, data: {confirm: "Are you sure you want to delete this user?"} %>